services:
  # PostgreSQL Database
  db:
    image: postgres:18
    container_name: inst_parser_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql
    ports:
      - "5440:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - inst_parser_network
  redis:
    image: redis:8
    container_name: inst_parser_redis
    restart: unless-stopped
    command:
      ["redis-server", "--maxmemory 200mb", "--maxmemory-policy", "allkeys-lru"]
    volumes:
      - redisdata:/var/lib/redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - inst_parser_network

volumes:
  pgdata:
  redisdata:

networks:
  inst_parser_network:
    driver: bridge
